### ISSUE TITLE
Github sponsoring

### ISSUE THREAD

**Issue by eithe** [placemark/togeojson#126]
Hi @tmcw, have you considered opening for sponsoring through Github Sponsor or something similar as a way for people to support this project and keep it maintained?

**Comment by tmcw** [comment]
Thanks - I'm happy to maintain this project for the foreseeable future, and am mostly time-limited just by having a [day job](https://www.val.town/). Sponsorship unfortunately wouldn't really get me much more time.

Code contributions rather than financial are really what would help keep this project going! I think it's in a pretty good spot already, already solving quite a few people's problems cleanly, and it's unlikely to be the root of any security flaw. There are definitely a few more things to fix and implement, though, and contributions would be welcome for any of them.
