### ISSUE TITLE
Styles from kml are not included

### ISSUE THREAD

**Issue by zdila** [placemark/togeojson#60]
I have created [simple kml with one placemark and one polygon](https://github.com/placemark/togeojson/files/8155161/Project.2.kml.gz), styled placemark icon and polygon color but none of the styles are in the GeoJSON feature properties.

Output GeoJSON:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          21.00062301000721,
          48.77257131826958,
          1011.317797185818
        ]
      },
      "properties": {
        "name": "Untitled Placemark",
        "styleUrl": "#__managed_style_04D1BA179420769B4A67",
        "styleMapHash": {
          "normal": "#__managed_style_1AF19DBC7E20769B4A67",
          "highlight": "#__managed_style_21BB934A3420769B4A67"
        },
        "description": "<div>Ahoj <b>PM</b></div>"
      },
      "id": "00A083AD2520769B213A"
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              20.99533143425753,
              48.76385474037835,
              817.5844849086294
            ],
            [
              21.00506376944139,
              48.76355632184772,
              896.3736545453368
            ],
            [
              21.00499721332549,
              48.77057344889175,
              1026.856093377534
            ],
            [
              20.99495695589513,
              48.77073832155815,
              991.0859038879247
            ],
            [
              20.99533143425753,
              48.76385474037835,
              817.5844849086294
            ]
          ]
        ]
      },
      "properties": {
        "name": "Untitled Polygon",
        "styleUrl": "#__managed_style_01C13F4A1E20769D5922",
        "styleMapHash": {
          "normal": "#__managed_style_1CAC85685820769D5922",
          "highlight": "#__managed_style_24D42D73B520769D5922"
        }
      },
      "id": "0F66A23B9820769D44FC"
    }
  ]
}
```

Should styles be included or it is just not supported by the library?

Thank you

**Comment by tmcw** [comment]
GeoJSON the specification doesn't include the ability to style features. KML is one of the only formats - possibly the only data format - to include styles. So far, toGeoJSON hasn't translated KML styles into anything opinionated because there is no core GeoJSON standard. However, I'm thinking about translating them to a subset of [simplestyle-spec](https://github.com/mapbox/simplestyle-spec). That won't guarantee that those styles show up anywhere that GeoJSON is displayed, but it'll give people the option of interpreting those styles on their map.

**Comment by zdila** [comment]
> That won't guarantee that those styles show up anywhere that GeoJSON is displayed, but it'll give people the option of interpreting those styles on their map.

I am processing GeoJSON programatically after it is parsed with togeojson so I would accept any way of getting props. It could even be included in `x-togeojson-styles` in the properties :-). But I like symplestyle-spec more.

**Comment by tmcw** [comment]
Okay, so digging into this more, and:

- I forgot, but we did implement simplestyle-spec support in toGeoJSON years back 😆
- The reason why this isn't parsed is because this KML has a `gx:CascadingStyle` element that I haven't ever seen before and isn't mentioned by any specification I can find. This is, apparently, just something that Google Earth does ad-hoc.
