### ISSUE TITLE
Publishing various converters as separate components

### ISSUE THREAD

**Issue by Raruto** [placemark/togeojson#73]
Hi tom,

if I'm not mistaken at present the only way to import the library into the browser (excluding [modules](https://github.com/placemark/togeojson#browser) usage) is through importing the whole bundle which ships all three parsers: KML, TCX, & GPX (am I wrong?).

I usually do something like this in my plugins:

```html
<script type="text/javascript">

  import('https://unpkg.com/@tmcw/togeojson@4.7.0/dist/togeojson.umd.js').then(()=> { /* do stuff */ } );

</script>
```

In your opinion, in order to avoid downloading unused code, it would also be possible to do such a thing?

```html
<script type="text/javascript">

  import('https://unpkg.com/@tmcw/togeojson@4.7.0/dist/togeojson.gpx.umd.js').then(()=> { /* GPX stuff */ } );
  import('https://unpkg.com/@tmcw/togeojson@4.7.0/dist/togeojson.kml.umd.js').then(()=> { /* KML stuff */ } );
  import('https://unpkg.com/@tmcw/togeojson@4.7.0/dist/togeojson.tcx.umd.js').then(()=> { /* TCX stuff */ } );
  import('https://unpkg.com/@tmcw/togeojson@4.7.0/dist/togeojson.umd.js').then(()=> { /* KML, TCX, & GPX  stuff */ } );

</script>
```

I think it's not unusual to work with a single format at a time (or at least one file at a time) and in any case it already seemed to me that this library was quite already well structured to achieve this result.

_Have a nice day,
Raruto_

---

**PS** i saw that you are working on [placemark.io](https://www.placemark.io/), may i ask what will be the new cdn url after version 4.7? (maybe I'm wrong, but I don't think anything has been published on npm for version 5.x or so).

**Comment by tmcw** [comment]
Hi Raruto,

I think this is a bit too narrow a case. toGeoJSON is currently around 3.7kb minified & gzipped – very small compared to nearly any npm module. And people using it with any module-supporting bundler can use tree-shaking to do `import { kml }` and only get the KML-related code. Building 3+ new dists that would make the install directions more complicated to shave 3.7kb down to, say, 2kb, just doesn't seem worth the complexity. Using import & bundle shaking is a much more robust way to include what you use than having additional entrypoints.

The 5.x prereleases are on npm, but are not the default because they're tagged prerelease - https://www.npmjs.com/package/@tmcw/togeojson . I'll push a 5.0.0 release once everything is very tested in the placemark environment.

**Comment by Raruto** [comment]
> I think this is a bit too narrow a case. toGeoJSON is currently around 3.7kb minified & gzipped – very small compared to nearly any npm module. And people using it with any module-supporting bundler can use tree-shaking to do import { kml } and only get the KML-related code. 

For what it's worth, from my little experience, many people who use leaflet aren't that well versed with modern javascript (e.g. some university researchers) or just don't have time to learn deepen (some are just a bit reluctant to use typescript or modules), but this is not so much the problem.

> Building 3+ new dists that would make the install directions more complicated to shave 3.7kb down to, say, 2kb, just doesn't seem worth the complexity.

Actually, my initial idea was more to also publish the `lib` folder (as well as the `dist` directory) to unpkg.com:

```html
<script type="text/javascript">

  import('https://unpkg.com/@tmcw/togeojson@4.7.0/lib/gpx.js').then(()=> { /* GPX stuff */ } );
  import('https://unpkg.com/@tmcw/togeojson@4.7.0/lib/kml.js').then(()=> { /* KML stuff */ } );
  import('https://unpkg.com/@tmcw/togeojson@4.7.0/lib/tcx.js').then(()=> { /* TCX stuff */ } );
  import('https://unpkg.com/@tmcw/togeojson@4.7.0/dist/togeojson.umd.js').then(()=> { /* KML, TCX, & GPX  stuff */ } );

</script>
```

but I was wondering, because given the latest updates I don't know if it's still so feasible (it's just to have a confrontation with you, I have no urgency or expectation about it). 

---

> The 5.x prereleases are on npm, but are not the default because they're tagged prerelease - https://www.npmjs.com/package/@tmcw/togeojson . I'll push a 5.0.0 release once everything is very tested in the placemark environment.

You're right 🤦‍♂️, forgive me if I ask trivial questions but in everyday life I use these tools much less than you do (and there is always something I forget to check).

**Comment by tmcw** [comment]
Previously, yes, I think people could import directly from the directories, but after the TypeScript switch that isn't possible and would require more work.

I think the problem here is just that the user segment doesn't exist. A university researcher using leaflet who is not well versed in modern javascript should not be worrying about an extra 500 bytes of JavaScript code being loaded, in any case. It's just not a significant case. Leaflet is going to be 80x that size. Those who may care about that kind of optimization - very few - will be using a bundler.
